version: 1.0
jobs:
  Build_and_Scan:
    name: "Build and Security Scan"
    parameters:
      env.POLARIS_SERVER_URL: "https://poc.polaris.blackduck.com"
      env.BLACKDUCK_API_TOKEN: "jrgodvf36h0gncgq430cc0htnl86o8vpdc44ghdjulhbvfm4ctknff00hudrg18fgok7cpd0qldnk"
    steps:
      - name: "Compile Application"
        type: script
        script-content: |
          echo "Install dependencies..."
          npm install
